### ISSUE TITLE
Error with JWTBlackList in rails 6

### ISSUE THREAD

**Issue by A-Boudi** [waiting-for-dev/devise-jwt#153]
Hi,

Following the readme file to create a [JWTBlackList](https://github.com/waiting-for-dev/devise-jwt#blacklist) results into an error.

```
uninitialized constant User (call 'User.connection' to establish a connection)::JWTBlacklist (NameError) Did you mean?  JwtBlacklist
```

## Expected behavior
No error.

## Actual behavior
Throws error
```
`<class:User>': uninitialized constant User (call 'User.connection' to establish a connection)::JWTBlacklist (NameError) Did you mean?  JwtBlacklist
```
## Steps to Reproduce the Problem

1. Create a new rails app
2. Install Devise
3. Install Devise-jwt
4. Create JWTBlacklist model (jwt_blacklist.rb) and migration
5. Add the following to User model (user.rb)
```
  devise :database_authenticatable,
         :jwt_authenticatable, jwt_revocation_strategy: JWTBlacklist
```

## Debugging information

`devise-jwt` versions `0.5.9` and `0.6.0`
`rails` version `6.0.0`

### Downgrade to 5.2
Downgrading `config.load_defaults 6.0` to `5.2`.

### Rename filename of JwtBlacklist model
renaming filename of JwtBlacklist model from`jwt_blacklist.rb` to `j_w_t_blacklist.rb`.

### Rename JwtBlacklist model
Renaming model from `JwtBlacklist` to `JwtBlacklist`

**Comment by waiting-for-dev** [comment]
Hey @A-Boudi , thanks for reporting.

I haven't used Rails for a while. Probably it has changed inference rules in 6.0. What about if you just name the model `JwtBlacklist` instead of `JWTBlacklist`? I guess this way you won't have to downgrade `load_defaults` nor rename the file.

**Comment by A-Boudi** [comment]
@waiting-for-dev thanks. Renaming the model works fine. I just wanted to raise this issue so the documentation would be updated.

**Comment by waiting-for-dev** [comment]
Thanks, I will.

**Comment by waiting-for-dev** [comment]
Sorry, but I can't reproduce the issue. I updated the application that is used in the tests of this library to Rails 6, the model is called `JWTBlacklist` and there is no problem...

https://github.com/waiting-for-dev/devise-jwt/blob/master/spec/fixtures/rails_app/app/models/jwt_blacklist.rb

Am I missing something?

**Comment by A-Boudi** [comment]
The issue happens when the `JWTBlacklist` model is called from the `User` model for the `jwt_revocation_strategy` parameter.

Here is the code sample that replicate this issue:
https://github.com/A-Boudi/devise-jwt-issue

**Comment by waiting-for-dev** [comment]
I can reproduce the issue in your repo, but it's strange because it doesn't happen in the fixture app:

https://github.com/waiting-for-dev/devise-jwt/blob/master/spec/fixtures/rails_app/app/models/jwt_with_blacklist_user.rb#L5

**Comment by waiting-for-dev** [comment]
Ok, it is because of `config.load_defaults`, which in the fixture app are not set to 6.0. I'll upgrade the fixture app when I find the time or someone submits a PR. About the documentation, it is fixed in master. Thanks for reporting.

**Comment by aonomike** [comment]
I have this same problem, I have tried to resolve by installing my gem from git as below
```
# devise-jwt
gem 'devise-jwt', git: 'https://github.com/waiting-for-dev/devise-jwt.git'
```
This still did not resolve, anything I am missing maybe?

**Comment by aonomike** [comment]
Thanks guys, this works for me on rails 6.

**Comment by thubamamba** [comment]
I am facing this error and have no ida how to rectify it.

![Screenshot 2020-02-24 at 10 52 56](https://user-images.githubusercontent.com/22769109/75138848-e3604400-56f3-11ea-98e4-53b5231521e8.png)

**Comment by waiting-for-dev** [comment]
It's related with #159. I'm currently working to fix it. For now, lock "dry-configurable" dependency to 0.9 in your Gemfile and you'be safe

**Comment by mayankdedhia** [comment]
> 
> 
> It's related with #159. I'm currently working to fix it. For now, lock "dry-configurable" dependency to 0.9 in your Gemfile and you'be safe

This didn't work, renaming the file worked

**Comment by StellarProcy** [comment]
There is no more Blacklist, now it's Denylist.

**Comment by jamesstaub** [comment]
👍  thanks @StellarProcy

**Comment by shengchalover** [comment]
looks like all the dislikes and negative reactions have been silently cleaned from this thread
